name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - production

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: npm install && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0.7.1
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
                  projectId: pricing-kingsmangolf-com
                  channelId: live
